import XCTest
@testable import VoicenoteAnki

final class FlashcardTests: XCTestCase {

    // MARK: - Difficulty

    func testDifficultyRawValues() {
        XCTAssertEqual(Difficulty.easy.rawValue, "easy")
        XCTAssertEqual(Difficulty.medium.rawValue, "medium")
        XCTAssertEqual(Difficulty.hard.rawValue, "hard")
    }

    func testDifficultyLabels() {
        XCTAssertEqual(Difficulty.easy.label, "Easy")
        XCTAssertEqual(Difficulty.medium.label, "Medium")
        XCTAssertEqual(Difficulty.hard.label, "Hard")
    }

    func testDifficultyColors() {
        XCTAssertEqual(Difficulty.easy.color, "green")
        XCTAssertEqual(Difficulty.medium.color, "orange")
        XCTAssertEqual(Difficulty.hard.color, "red")
    }

    func testDifficultyAllCases() {
        XCTAssertEqual(Difficulty.allCases.count, 3)
        XCTAssertTrue(Difficulty.allCases.contains(.easy))
        XCTAssertTrue(Difficulty.allCases.contains(.medium))
        XCTAssertTrue(Difficulty.allCases.contains(.hard))
    }

    func testDifficultyInitFromRawValue() {
        XCTAssertEqual(Difficulty(rawValue: "easy"), .easy)
        XCTAssertEqual(Difficulty(rawValue: "medium"), .medium)
        XCTAssertEqual(Difficulty(rawValue: "hard"), .hard)
        XCTAssertNil(Difficulty(rawValue: "unknown"))
    }

    // MARK: - Flashcard Initialization

    func testFlashcardDefaultInitialization() {
        let noteID = UUID()
        let card = Flashcard(front: "What is 2+2?", back: "4", sourceNoteID: noteID)

        XCTAssertEqual(card.front, "What is 2+2?")
        XCTAssertEqual(card.back, "4")
        XCTAssertEqual(card.difficulty, .medium)
        XCTAssertTrue(card.tags.isEmpty)
        XCTAssertFalse(card.isStarred)
        XCTAssertEqual(card.reviewCount, 0)
        XCTAssertNil(card.lastReviewedAt)
        XCTAssertEqual(card.sourceNoteID, noteID)
        XCTAssertFalse(card.id.uuidString.isEmpty)
    }

    func testFlashcardFullInitialization() {
        let noteID = UUID()
        let id = UUID()
        let card = Flashcard(
            id: id,
            front: "Capital of France?",
            back: "Paris",
            tags: ["geography", "europe"],
            difficulty: .easy,
            sourceNoteID: noteID
        )

        XCTAssertEqual(card.id, id)
        XCTAssertEqual(card.front, "Capital of France?")
        XCTAssertEqual(card.back, "Paris")
        XCTAssertEqual(card.tags, ["geography", "europe"])
        XCTAssertEqual(card.difficulty, .easy)
        XCTAssertEqual(card.sourceNoteID, noteID)
    }

    func testFlashcardHardDifficulty() {
        let noteID = UUID()
        let card = Flashcard(front: "Q", back: "A", difficulty: .hard, sourceNoteID: noteID)
        XCTAssertEqual(card.difficulty, .hard)
    }

    // MARK: - Codable

    func testFlashcardEncodeDecode() throws {
        let noteID = UUID()
        let original = Flashcard(
            front: "Term",
            back: "Definition",
            tags: ["swift", "ios"],
            difficulty: .hard,
            sourceNoteID: noteID
        )

        let data = try JSONEncoder().encode(original)
        let decoded = try JSONDecoder().decode(Flashcard.self, from: data)

        XCTAssertEqual(decoded, original)
        XCTAssertEqual(decoded.front, original.front)
        XCTAssertEqual(decoded.back, original.back)
        XCTAssertEqual(decoded.tags, original.tags)
        XCTAssertEqual(decoded.difficulty, original.difficulty)
        XCTAssertEqual(decoded.sourceNoteID, original.sourceNoteID)
    }

    func testFlashcardEncodeDecodeEmptyTags() throws {
        let noteID = UUID()
        let original = Flashcard(front: "Q", back: "A", sourceNoteID: noteID)
        let data = try JSONEncoder().encode(original)
        let decoded = try JSONDecoder().decode(Flashcard.self, from: data)
        XCTAssertTrue(decoded.tags.isEmpty)
    }

    // MARK: - Equatable

    func testFlashcardEqualityById() {
        let noteID = UUID()
        let sharedID = UUID()
        let card1 = Flashcard(id: sharedID, front: "Q", back: "A", sourceNoteID: noteID)
        let card2 = Flashcard(id: sharedID, front: "Q", back: "A", sourceNoteID: noteID)
        XCTAssertEqual(card1, card2)
    }

    func testFlashcardInequalityDifferentIds() {
        let noteID = UUID()
        let card1 = Flashcard(front: "Q", back: "A", sourceNoteID: noteID)
        let card2 = Flashcard(front: "Q", back: "A", sourceNoteID: noteID)
        // Different UUIDs generated by default
        XCTAssertNotEqual(card1, card2)
    }

    // MARK: - Study state mutation

    func testFlashcardStudyStateMutation() {
        let noteID = UUID()
        var card = Flashcard(front: "Q", back: "A", sourceNoteID: noteID)

        card.isStarred = true
        card.reviewCount = 5
        card.lastReviewedAt = Date()

        XCTAssertTrue(card.isStarred)
        XCTAssertEqual(card.reviewCount, 5)
        XCTAssertNotNil(card.lastReviewedAt)
    }

    func testFlashcardFrontBackMutation() {
        let noteID = UUID()
        var card = Flashcard(front: "Old front", back: "Old back", sourceNoteID: noteID)
        card.front = "New front"
        card.back = "New back"
        XCTAssertEqual(card.front, "New front")
        XCTAssertEqual(card.back, "New back")
    }
}
